# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  IMAGE_NAME: strzaa/flask_webside
  IMAGE_TAG: flaskApp


jobs:
- job: build_and_push_image
  displayName: 'Build and Push Docker Image'
  steps:
  
  - task: DockerInstaller@0
    inputs:
      dockerVersion: '17.09.0-ce'
    
  - task: Docker@2
    inputs:
      containerRegistry: 'DockerHubCon'
      command: 'login'
  
  - bash: |
      docker build -t $IMAGE_NAME:$IMAGE_TAG ./python/
      docker push $IMAGE_NAME:$IMAGE_TAG
      
- job: deploy
  displayName: 'Deploy to Azure VM'
  steps:

  - task: Docker@2
    inputs:
      containerRegistry: 'DockerHubCon'
      command: 'login'
    
  - task: DownloadSecureFile@1
    name: secure_files
    inputs:
      secureFile: 'azure_flask'

  - bash: |
      chmod 600 $(secure_files.secureFilePath)
      ssh -o StrictHostKeyChecking=no -i $(secure_files.secureFilePath) strzaa@23.101.138.188 "
            docker ps -qa | xargs -r docker stop && docker ps -qa | xargs -r docker rm &&
            docker run -d -p 5000:5000 -v /python/exel:/app/exel $IMAGE_NAME:$IMAGE_TAG "

      

