# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  IMAGE_NAME: strzaa/flask_webside
  IMAGE_TAG: flaskApp


jobs:
- job: build_and_push_image
  displayName: 'Build and Push Docker Image'
  steps:
  - task: DockerInstaller@0
    inputs:
      dockerVersion: '17.09.0-ce'
    
  - task: Docker@2
    inputs:
      containerRegistry: 'DockerHubCon'
      command: 'login'
  
  - bash: |
      docker build -t $IMAGE_NAME:$IMAGE_TAG ./python/
      docker push $IMAGE_NAME:$IMAGE_TAG


