version: '3.0'

services:
  python:
    container_name: flask
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./python/exel:/app/exel
    

      
  